# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  ${CA_REG_PEER_HOST}:

# networks:
#   test:
#     name: fabric_test

networks:
    fabric:
        external:
            name: fabric

services:

  ${CA_REG_PEER_HOST}:
    container_name: ${CA_REG_PEER_HOST}
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=${CA_REG_PEER_HOST}
      - CORE_PEER_ADDRESS=${CA_REG_PEER_HOST}:${SET_PEER_LISTENPORT}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${SET_PEER_LISTENPORT}
      - CORE_PEER_CHAINCODEADDRESS=${CA_REG_PEER_HOST}:${SET_CHAINCODE_SERPORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${SET_CHAINCODE_SERPORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${CA_REG_PEER_HOST}:${SET_PEER_LISTENPORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${CA_REG_PEER_HOST}:${SET_PEER_LISTENPORT}
      - CORE_PEER_LOCALMSPID=${CORE_PEER_LOCALMSPID}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=${CA_REG_PEER_HOST}:${SET_OPERATIONS_LISTENPORT}
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG=${SET_CHAINCODE_CONFIG}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ${FABRIC_CA_CLIENT_HOME}/peers/${CA_REG_PEER_HOST}:/etc/hyperledger/fabric
        - ${CA_REG_PEER_HOST}:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - ${SET_PEER_LISTENPORT}:${SET_PEER_LISTENPORT}
      - ${SET_OPERATIONS_LISTENPORT}:${SET_OPERATIONS_LISTENPORT}
    networks:
      - fabric
